### ISSUE TITLE
Not working with dry-validation > 1.0

### ISSUE THREAD

**Issue by knovoselic** [bloom-solutions/dry-validation-matchers#17]
Are there any plans to fix this library to work with the newest `dry-validation` gem? Looks like v1.0 introduced a lot of breaking changes.

**Comment by ramontayag** [comment]
We'll probably upgrade this when we upgrade our apps to 1.0, but that's not our backlog at the moment. Any pull requests are welcome!

**Comment by knovoselic** [comment]
I see, thanks. Unfortunately, don't think I have any bandwidth for this, but if it changes I'll submit a PR :)
